// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(StockMarketDbContext))]
    partial class StockMarketDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.BuyOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndTimeOfOrder")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("float(15)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("BuyOrders", null, t =>
                        {
                            t.HasCheckConstraint("CHK_BuyOrders_Price", "[Price] > 0 AND [Price] <= 100000");

                            t.HasCheckConstraint("CHK_BuyOrders_Quantity", "[Quantity] > 0 AND [Quantity] <= 100000");

                            t.HasCheckConstraint("CHK__BuyOrders_OrderDate_Min", "[DateAndTimeOfOrder] >= '2000-01-01'");
                        });
                });

            modelBuilder.Entity("Entities.SellOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAndTimeOfOrder")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("float(15)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StockSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("SellOrders", null, t =>
                        {
                            t.HasCheckConstraint("CHK_SellOrders_Price", "[Price] > 0 AND [Price] <= 100000");

                            t.HasCheckConstraint("CHK_SellOrders_Quantity", "[Quantity] > 0 AND [Quantity] <= 100000");

                            t.HasCheckConstraint("CHK__SellOrders_OrderDate_Min", "[DateAndTimeOfOrder] >= '2000-01-01'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
